Welcome_Center_Site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from first_app import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^admin/', admin.site.urls),
]

first_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Members(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    wc_id = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Attendance(models.Model):

    member = models.ForeignKey(Members, on_delete = models.CASCADE)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return str(self.timestamp) + ': ' + self.memeber.__str__()

first_app/forms.py
from django import forms


class ImageForm(forms.Form):
    img = forms.CharField(widget=forms.HiddenInput(), required=False)

first_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from first_app.models import Attendance
from first_app.forms import ImageForm

import re
import base64
import zbarlight
from PIL import Image
from io import BytesIO

# Create your views here.


def index(request):
    form = ImageForm()
    code = 'this is the qrcode'

    if request.method == 'POST':
        data = ImageForm(request.POST)
        if data.is_valid():
            dataUrlPattern = re.compile('data:image/(png|jpeg);base64,(.*)$')
            image_data = data.cleaned_data['img']
            image_data = dataUrlPattern.match(image_data).group(2)
            image_data = image_data.encode()
            image_data = base64.b64decode(image_data)
            image = Image.open(BytesIO(image_data))
            code = zbarlight.scan_codes('qrcode', image)
            print(code)
        else:
            print('form is not valid')

    return render(request, 'index.html', {"code": code, "form": form})

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Welcome Center</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  </head>

  <body>
    <div class="jumbotron">
      <h2>CCF Welcome Center</h2>
      <div class="video-container">
          <video autoplay="true" class="videoElement">
          </video>
      </div>
      <div class="list-container">
        <form method="post">
          {% csrf_token %}
          {{form}}
          <input type="button" name="Submit" value="Submit">
        </form>
        <h3>{{code}}</h3>
      </div>
    </div>

    <script>

      // Access browser webcam
      const constraints = {
        audio: false,
        video: true
      };
      const video = document.querySelector('video');

      function handleSuccess(stream) {
        video.srcObject = stream;
      }

      function handleError(error) {
        console.log(err.name + ": " + err.message);
      }

      navigator.mediaDevices.getUserMedia(constraints).
        then(handleSuccess).catch(handleError);

      //Create Canvas
      const canvas = document.createElement('canvas');

      video.onclick = function() {
        canvas.width = video.videoWidth;
        canvas.height = video.videoHeight;
        canvas.getContext('2d').drawImage(video, 0, 0);
        // Other browsers will fall back to image/png
        var img= canvas.toDataURL();

        $('#id_img').val(img);
        $('form').submit();

      };


    </script>

  </body>
</html>

templates/jumbo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Welcome Center</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="jumbotron-narrow.css" rel="stylesheet">



  </head>

  <body>

    <div class="container">
      <div class="header clearfix">
        <nav class = "navbar navbar-dark">
          <ul class="nav nav-pills pull-right">

          </ul>
        </nav>
        <h3 class="text-muted">Welcome Center</h3>
      </div>

      <div class="jumbotron">
        <div class="video-container">
          <video autoplay="true" class="video-stream" width="500" height="400" border = "10px">

          </video>
        </div>

        <p><a class="btn btn-lg btn-success" href="#" role="button">Done</a></p>
      </div>

      <div class="row marketing">
        <div class="col-lg-6">
          <h4>John Doe</h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

        </div>
        <div class="video-container">

        </div>
      </div>

      <footer class="footer">
        <p>&copy; 2016 Company, Inc.</p>
      </footer>

    </div> <!-- /container -->


    <script>
      const constraints = {
        video: true
      };

      const video = document.querySelector('video');

      function handleSuccess(stream) {
        video.srcObject = stream;
      }

      function handleError(error) {
        console.error('Reeeejected!', error);
      }

      navigator.mediaDevices.getUserMedia(constraints).
        then(handleSuccess).catch(handleError);
    </script>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>